Use tadb;
set foreign_key_checks = 0;
drop table admins;
drop table classes;
drop table quizzes;
drop table schools;
drop table students;
drop table students_classes;
#drop table students_teachers;
drop table students_quizzes;
drop table teachers;
drop table topics;
drop table users;
set foreign_key_checks = 1;
